/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Component from './Component';

/**
 * The Coloring model module.
 * @module model/Coloring
 * @version v1
 */
class Coloring {
    /**
     * Constructs a new <code>Coloring</code>.
     * @alias module:model/Coloring
     * @param color {String} 
     * @param components {Array.<module:model/Component>} 
     */
    constructor(color, components) { 
        
        Coloring.initialize(this, color, components);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, color, components) { 
        obj['color'] = color;
        obj['components'] = components;
    }

    /**
     * Constructs a <code>Coloring</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Coloring} obj Optional instance to populate.
     * @return {module:model/Coloring} The populated <code>Coloring</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Coloring();

            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
            if (data.hasOwnProperty('components')) {
                obj['components'] = ApiClient.convertToType(data['components'], [Component]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} color
 */
Coloring.prototype['color'] = undefined;

/**
 * @member {Array.<module:model/Component>} components
 */
Coloring.prototype['components'] = undefined;






export default Coloring;

