/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CheckPlan from './CheckPlan';
import CheckerResult from './CheckerResult';
import Model from './Model';
import User from './User';

/**
 * The IfcChecker model module.
 * @module model/IfcChecker
 * @version 0.0.0
 */
class IfcChecker {
    /**
     * Constructs a new <code>IfcChecker</code>.
     * @alias module:model/IfcChecker
     * @param id {Number} 
     * @param ifc {module:model/Model} 
     * @param creator {module:model/User} 
     * @param results {Array.<module:model/CheckerResult>} 
     * @param createdAt {Date} 
     * @param updatedAt {Date} 
     * @param checkplan {module:model/CheckPlan} 
     */
    constructor(id, ifc, creator, results, createdAt, updatedAt, checkplan) { 
        
        IfcChecker.initialize(this, id, ifc, creator, results, createdAt, updatedAt, checkplan);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, ifc, creator, results, createdAt, updatedAt, checkplan) { 
        obj['id'] = id;
        obj['ifc'] = ifc;
        obj['creator'] = creator;
        obj['results'] = results;
        obj['created_at'] = createdAt;
        obj['updated_at'] = updatedAt;
        obj['checkplan'] = checkplan;
    }

    /**
     * Constructs a <code>IfcChecker</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IfcChecker} obj Optional instance to populate.
     * @return {module:model/IfcChecker} The populated <code>IfcChecker</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IfcChecker();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('ifc')) {
                obj['ifc'] = ApiClient.convertToType(data['ifc'], Model);
            }
            if (data.hasOwnProperty('creator')) {
                obj['creator'] = ApiClient.convertToType(data['creator'], User);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('results')) {
                obj['results'] = ApiClient.convertToType(data['results'], [CheckerResult]);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('checkplan')) {
                obj['checkplan'] = ApiClient.convertToType(data['checkplan'], CheckPlan);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
IfcChecker.prototype['id'] = undefined;

/**
 * @member {module:model/Model} ifc
 */
IfcChecker.prototype['ifc'] = undefined;

/**
 * @member {module:model/User} creator
 */
IfcChecker.prototype['creator'] = undefined;

/**
 * @member {String} name
 */
IfcChecker.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/CheckerResult>} results
 */
IfcChecker.prototype['results'] = undefined;

/**
 * @member {Date} created_at
 */
IfcChecker.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
IfcChecker.prototype['updated_at'] = undefined;

/**
 * @member {module:model/CheckPlan} checkplan
 */
IfcChecker.prototype['checkplan'] = undefined;






export default IfcChecker;

