/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The IfcCheckerResults model module.
 * @module model/IfcCheckerResults
 * @version 0.0.0
 */
class IfcCheckerResults {
    /**
     * Constructs a new <code>IfcCheckerResults</code>.
     * @alias module:model/IfcCheckerResults
     * @param checker {Number} 
     */
    constructor(checker) { 
        
        IfcCheckerResults.initialize(this, checker);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, checker) { 
        obj['checker'] = checker;
    }

    /**
     * Constructs a <code>IfcCheckerResults</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IfcCheckerResults} obj Optional instance to populate.
     * @return {module:model/IfcCheckerResults} The populated <code>IfcCheckerResults</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IfcCheckerResults();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('error_detail')) {
                obj['error_detail'] = ApiClient.convertToType(data['error_detail'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'String');
            }
            if (data.hasOwnProperty('collisions')) {
                obj['collisions'] = ApiClient.convertToType(data['collisions'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('checker')) {
                obj['checker'] = ApiClient.convertToType(data['checker'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
IfcCheckerResults.prototype['id'] = undefined;

/**
 * @member {String} error_detail
 */
IfcCheckerResults.prototype['error_detail'] = undefined;

/**
 * @member {module:model/IfcCheckerResults.StatusEnum} status
 */
IfcCheckerResults.prototype['status'] = undefined;

/**
 * @member {String} result
 */
IfcCheckerResults.prototype['result'] = undefined;

/**
 * @member {String} collisions
 */
IfcCheckerResults.prototype['collisions'] = undefined;

/**
 * @member {Date} created_at
 */
IfcCheckerResults.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
IfcCheckerResults.prototype['updated_at'] = undefined;

/**
 * @member {Number} checker
 */
IfcCheckerResults.prototype['checker'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
IfcCheckerResults['StatusEnum'] = {

    /**
     * value: "C"
     * @const
     */
    "C": "C",

    /**
     * value: "P"
     * @const
     */
    "P": "P",

    /**
     * value: "E"
     * @const
     */
    "E": "E"
};



export default IfcCheckerResults;

