/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PatchedPositioningPlanRequest model module.
 * @module model/PatchedPositioningPlanRequest
 * @version 0.0.0
 */
class PatchedPositioningPlanRequest {
    /**
     * Constructs a new <code>PatchedPositioningPlanRequest</code>.
     * @alias module:model/PatchedPositioningPlanRequest
     */
    constructor() { 
        
        PatchedPositioningPlanRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchedPositioningPlanRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchedPositioningPlanRequest} obj Optional instance to populate.
     * @return {module:model/PatchedPositioningPlanRequest} The populated <code>PatchedPositioningPlanRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedPositioningPlanRequest();

            if (data.hasOwnProperty('translation_x')) {
                obj['translation_x'] = ApiClient.convertToType(data['translation_x'], 'Number');
            }
            if (data.hasOwnProperty('translation_y')) {
                obj['translation_y'] = ApiClient.convertToType(data['translation_y'], 'Number');
            }
            if (data.hasOwnProperty('rotate_z')) {
                obj['rotate_z'] = ApiClient.convertToType(data['rotate_z'], 'Number');
            }
            if (data.hasOwnProperty('scale')) {
                obj['scale'] = ApiClient.convertToType(data['scale'], 'Number');
            }
            if (data.hasOwnProperty('opacity')) {
                obj['opacity'] = ApiClient.convertToType(data['opacity'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} translation_x
 */
PatchedPositioningPlanRequest.prototype['translation_x'] = undefined;

/**
 * @member {Number} translation_y
 */
PatchedPositioningPlanRequest.prototype['translation_y'] = undefined;

/**
 * @member {Number} rotate_z
 */
PatchedPositioningPlanRequest.prototype['rotate_z'] = undefined;

/**
 * @member {Number} scale
 */
PatchedPositioningPlanRequest.prototype['scale'] = undefined;

/**
 * @member {Number} opacity
 */
PatchedPositioningPlanRequest.prototype['opacity'] = undefined;






export default PatchedPositioningPlanRequest;

