/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FolderPermissionEnum from './FolderPermissionEnum';

/**
 * The PatchedFolderWithoutChildrenRequest model module.
 * @module model/PatchedFolderWithoutChildrenRequest
 * @version 0.0.0
 */
class PatchedFolderWithoutChildrenRequest {
    /**
     * Constructs a new <code>PatchedFolderWithoutChildrenRequest</code>.
     * @alias module:model/PatchedFolderWithoutChildrenRequest
     */
    constructor() { 
        
        PatchedFolderWithoutChildrenRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PatchedFolderWithoutChildrenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PatchedFolderWithoutChildrenRequest} obj Optional instance to populate.
     * @return {module:model/PatchedFolderWithoutChildrenRequest} The populated <code>PatchedFolderWithoutChildrenRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PatchedFolderWithoutChildrenRequest();

            if (data.hasOwnProperty('parent_id')) {
                obj['parent_id'] = ApiClient.convertToType(data['parent_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('default_permission')) {
                obj['default_permission'] = ApiClient.convertToType(data['default_permission'], FolderPermissionEnum);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} parent_id
 */
PatchedFolderWithoutChildrenRequest.prototype['parent_id'] = undefined;

/**
 * Name of the folder
 * @member {String} name
 */
PatchedFolderWithoutChildrenRequest.prototype['name'] = undefined;

/**
 * Permission for a Folder
 * @member {module:model/FolderPermissionEnum} default_permission
 */
PatchedFolderWithoutChildrenRequest.prototype['default_permission'] = undefined;






export default PatchedFolderWithoutChildrenRequest;

