/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Priority model module.
 * @module model/Priority
 * @version 0.0.0
 */
class Priority {
    /**
     * Constructs a new <code>Priority</code>.
     * @alias module:model/Priority
     * @param priority {String} 
     */
    constructor(priority) { 
        
        Priority.initialize(this, priority);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, priority) { 
        obj['priority'] = priority;
    }

    /**
     * Constructs a <code>Priority</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Priority} obj Optional instance to populate.
     * @return {module:model/Priority} The populated <code>Priority</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Priority();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'String');
            }
            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
            if (data.hasOwnProperty('project')) {
                obj['project'] = ApiClient.convertToType(data['project'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Priority.prototype['id'] = undefined;

/**
 * @member {String} priority
 */
Priority.prototype['priority'] = undefined;

/**
 * @member {String} color
 */
Priority.prototype['color'] = undefined;

/**
 * This field is automatically provided by the route, you don't need to provide it in the body
 * @member {Number} project
 */
Priority.prototype['project'] = undefined;






export default Priority;

