/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProjectSize model module.
 * @module model/ProjectSize
 * @version 0.0.0
 */
class ProjectSize {
    /**
     * Constructs a new <code>ProjectSize</code>.
     * @alias module:model/ProjectSize
     */
    constructor() { 
        
        ProjectSize.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProjectSize</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProjectSize} obj Optional instance to populate.
     * @return {module:model/ProjectSize} The populated <code>ProjectSize</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProjectSize();

            if (data.hasOwnProperty('total_size')) {
                obj['total_size'] = ApiClient.convertToType(data['total_size'], 'Number');
            }
            if (data.hasOwnProperty('smart_data_size')) {
                obj['smart_data_size'] = ApiClient.convertToType(data['smart_data_size'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} total_size
 */
ProjectSize.prototype['total_size'] = undefined;

/**
 * @member {Number} smart_data_size
 */
ProjectSize.prototype['smart_data_size'] = undefined;






export default ProjectSize;

