/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RawClassification model module.
 * @module model/RawClassification
 * @version 0.0.0
 */
class RawClassification {
    /**
     * Constructs a new <code>RawClassification</code>.
     * @alias module:model/RawClassification
     * @param id {Number} 
     */
    constructor(id) { 
        
        RawClassification.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>RawClassification</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RawClassification} obj Optional instance to populate.
     * @return {module:model/RawClassification} The populated <code>RawClassification</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RawClassification();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('notation')) {
                obj['notation'] = ApiClient.convertToType(data['notation'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
RawClassification.prototype['id'] = undefined;

/**
 * @member {String} type
 */
RawClassification.prototype['type'] = undefined;

/**
 * @member {String} notation
 */
RawClassification.prototype['notation'] = undefined;

/**
 * @member {String} description
 */
RawClassification.prototype['description'] = undefined;






export default RawClassification;

