/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RawDefinitionRequest model module.
 * @module model/RawDefinitionRequest
 * @version 0.0.0
 */
class RawDefinitionRequest {
    /**
     * Constructs a new <code>RawDefinitionRequest</code>.
     * @alias module:model/RawDefinitionRequest
     */
    constructor() { 
        
        RawDefinitionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RawDefinitionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RawDefinitionRequest} obj Optional instance to populate.
     * @return {module:model/RawDefinitionRequest} The populated <code>RawDefinitionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RawDefinitionRequest();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('value_type')) {
                obj['value_type'] = ApiClient.convertToType(data['value_type'], 'String');
            }
            if (data.hasOwnProperty('unit_id')) {
                obj['unit_id'] = ApiClient.convertToType(data['unit_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} description
 */
RawDefinitionRequest.prototype['description'] = undefined;

/**
 * @member {String} name
 */
RawDefinitionRequest.prototype['name'] = undefined;

/**
 * @member {String} type
 */
RawDefinitionRequest.prototype['type'] = undefined;

/**
 * @member {String} value_type
 */
RawDefinitionRequest.prototype['value_type'] = undefined;

/**
 * @member {Number} unit_id
 */
RawDefinitionRequest.prototype['unit_id'] = undefined;






export default RawDefinitionRequest;

