/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RawMaterialOptions model module.
 * @module model/RawMaterialOptions
 * @version 0.0.0
 */
class RawMaterialOptions {
    /**
     * Constructs a new <code>RawMaterialOptions</code>.
     * @alias module:model/RawMaterialOptions
     * @param id {Number} 
     */
    constructor(id) { 
        
        RawMaterialOptions.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>RawMaterialOptions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RawMaterialOptions} obj Optional instance to populate.
     * @return {module:model/RawMaterialOptions} The populated <code>RawMaterialOptions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RawMaterialOptions();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('thickness')) {
                obj['thickness'] = ApiClient.convertToType(data['thickness'], 'Number');
            }
            if (data.hasOwnProperty('material_list')) {
                obj['material_list'] = ApiClient.convertToType(data['material_list'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
RawMaterialOptions.prototype['id'] = undefined;

/**
 * @member {Number} thickness
 */
RawMaterialOptions.prototype['thickness'] = undefined;

/**
 * @member {Array.<Number>} material_list
 */
RawMaterialOptions.prototype['material_list'] = undefined;






export default RawMaterialOptions;

