/**
 * BIMData API
 * BIMData API is a tool to interact with your models stored on BIMData’s servers.     Through the API, you can manage your projects, the clouds, upload your IFC files and manage them through endpoints.
 *
 * The version of the OpenAPI document: v1 (v1)
 * Contact: support@bimdata.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RawPropertyRequest model module.
 * @module model/RawPropertyRequest
 * @version 0.0.0
 */
class RawPropertyRequest {
    /**
     * Constructs a new <code>RawPropertyRequest</code>.
     * @alias module:model/RawPropertyRequest
     * @param defId {Number} 
     */
    constructor(defId) { 
        
        RawPropertyRequest.initialize(this, defId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, defId) { 
        obj['def_id'] = defId;
    }

    /**
     * Constructs a <code>RawPropertyRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RawPropertyRequest} obj Optional instance to populate.
     * @return {module:model/RawPropertyRequest} The populated <code>RawPropertyRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RawPropertyRequest();

            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], Object);
            }
            if (data.hasOwnProperty('def_id')) {
                obj['def_id'] = ApiClient.convertToType(data['def_id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} value
 */
RawPropertyRequest.prototype['value'] = undefined;

/**
 * @member {Number} def_id
 */
RawPropertyRequest.prototype['def_id'] = undefined;






export default RawPropertyRequest;

