/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TopicStatusRequest model module.
 * @module model/TopicStatusRequest
 * @version 0.0.0
 */
class TopicStatusRequest {
    /**
     * Constructs a new <code>TopicStatusRequest</code>.
     * @alias module:model/TopicStatusRequest
     * @param topicStatus {String} 
     */
    constructor(topicStatus) { 
        
        TopicStatusRequest.initialize(this, topicStatus);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, topicStatus) { 
        obj['topic_status'] = topicStatus;
    }

    /**
     * Constructs a <code>TopicStatusRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TopicStatusRequest} obj Optional instance to populate.
     * @return {module:model/TopicStatusRequest} The populated <code>TopicStatusRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TopicStatusRequest();

            if (data.hasOwnProperty('topic_status')) {
                obj['topic_status'] = ApiClient.convertToType(data['topic_status'], 'String');
            }
            if (data.hasOwnProperty('color')) {
                obj['color'] = ApiClient.convertToType(data['color'], 'String');
            }
            if (data.hasOwnProperty('project')) {
                obj['project'] = ApiClient.convertToType(data['project'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} topic_status
 */
TopicStatusRequest.prototype['topic_status'] = undefined;

/**
 * @member {String} color
 */
TopicStatusRequest.prototype['color'] = undefined;

/**
 * This field is automatically provided by the route, you don't need to provide it in the body
 * @member {Number} project
 */
TopicStatusRequest.prototype['project'] = undefined;






export default TopicStatusRequest;

