version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10
    working_directory: ~/repo


  restore_npm_cache: &restore_npm_cache
    restore_cache:
      keys:
        - v1-npm-{{ checksum "package.json" }}
        - v1-npm

jobs:
  test:
    <<: *container_config

    steps:
      - checkout
      - *restore_npm_cache

      - run:
          name: install dependencies
          command: |
            npm install
            npm install semantic-release
            npm install conventional-changelog-eslint

      - save_cache:
          key: v1-npm-{{ checksum "package.json" }}
          paths:
            - node_modules/
            - ~/.npm
            - ~/.cache

      - run: npm test

  release:
    <<: *container_config
    steps:
      - checkout
      - *restore_npm_cache
      - add_ssh_keys
      - run:
          name: Avoid hosts unknown for github
          command: echo -e " StrictHostKeyChecking no\n" >> ~/.ssh/config
      - run:
          name: build dist
          command: npm run build
      - run: npx semantic-release -e ./config/release.config.js --debug



workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
