/**
 * BIMData API
 * BIMData API documentation
 *
 * OpenAPI spec version: v1
 * Contact: contact@bimdata.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: unset
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BimdataApiClient);
  }
}(this, function(expect, BimdataApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BimdataApiClient.IfcCheckerIfc();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IfcCheckerIfc', function() {
    it('should create an instance of IfcCheckerIfc', function() {
      // uncomment below and update the code to test IfcCheckerIfc
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be.a(BimdataApiClient.IfcCheckerIfc);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property errorDetail (base name: "error_detail")', function() {
      // uncomment below and update the code to test the property errorDetail
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property structureFile (base name: "structure_file")', function() {
      // uncomment below and update the code to test the property structureFile
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property systemsFile (base name: "systems_file")', function() {
      // uncomment below and update the code to test the property systemsFile
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property zonesFile (base name: "zones_file")', function() {
      // uncomment below and update the code to test the property zonesFile
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property mapFile (base name: "map_file")', function() {
      // uncomment below and update the code to test the property mapFile
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property gltfFile (base name: "gltf_file")', function() {
      // uncomment below and update the code to test the property gltfFile
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property bvhTreeFile (base name: "bvh_tree_file")', function() {
      // uncomment below and update the code to test the property bvhTreeFile
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property updateCheckNeeded (base name: "update_check_needed")', function() {
      // uncomment below and update the code to test the property updateCheckNeeded
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property lastMailSent (base name: "last_mail_sent")', function() {
      // uncomment below and update the code to test the property lastMailSent
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property creator (base name: "creator")', function() {
      // uncomment below and update the code to test the property creator
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property document (base name: "document")', function() {
      // uncomment below and update the code to test the property document
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

    it('should have the property project (base name: "project")', function() {
      // uncomment below and update the code to test the property project
      //var instane = new BimdataApiClient.IfcCheckerIfc();
      //expect(instance).to.be();
    });

  });

}));
