/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.bimdata);
  }
}(this, function(expect, bimdata) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new bimdata.ViewpointRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ViewpointRequest', function() {
    it('should create an instance of ViewpointRequest', function() {
      // uncomment below and update the code to test ViewpointRequest
      //var instane = new bimdata.ViewpointRequest();
      //expect(instance).to.be.a(bimdata.ViewpointRequest);
    });

    it('should have the property index (base name: "index")', function() {
      // uncomment below and update the code to test the property index
      //var instane = new bimdata.ViewpointRequest();
      //expect(instance).to.be();
    });

    it('should have the property guid (base name: "guid")', function() {
      // uncomment below and update the code to test the property guid
      //var instane = new bimdata.ViewpointRequest();
      //expect(instance).to.be();
    });

    it('should have the property orthogonalCamera (base name: "orthogonal_camera")', function() {
      // uncomment below and update the code to test the property orthogonalCamera
      //var instane = new bimdata.ViewpointRequest();
      //expect(instance).to.be();
    });

    it('should have the property perspectiveCamera (base name: "perspective_camera")', function() {
      // uncomment below and update the code to test the property perspectiveCamera
      //var instane = new bimdata.ViewpointRequest();
      //expect(instance).to.be();
    });

    it('should have the property lines (base name: "lines")', function() {
      // uncomment below and update the code to test the property lines
      //var instane = new bimdata.ViewpointRequest();
      //expect(instance).to.be();
    });

    it('should have the property clippingPlanes (base name: "clipping_planes")', function() {
      // uncomment below and update the code to test the property clippingPlanes
      //var instane = new bimdata.ViewpointRequest();
      //expect(instance).to.be();
    });

    it('should have the property snapshot (base name: "snapshot")', function() {
      // uncomment below and update the code to test the property snapshot
      //var instane = new bimdata.ViewpointRequest();
      //expect(instance).to.be();
    });

    it('should have the property components (base name: "components")', function() {
      // uncomment below and update the code to test the property components
      //var instane = new bimdata.ViewpointRequest();
      //expect(instance).to.be();
    });

    it('should have the property tempId (base name: "temp_id")', function() {
      // uncomment below and update the code to test the property tempId
      //var instane = new bimdata.ViewpointRequest();
      //expect(instance).to.be();
    });

  });

}));
